# Groupby
- df.groupby
- df.groupby.first()
- df.groupby.get_group()

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("movies_data.csv")
df.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 979 entries, 0 to 978
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   star_rating     979 non-null    float64
 1   title           979 non-null    object
 2   content_rating  976 non-null    object
 3   genre           979 non-null    object
 4   duration        979 non-null    int64
 5   actors_list     979 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 46.0+ KB

In [4]:
df["genre"].unique()

array(['Crime', 'Action', 'Drama', 'Western', 'Adventure', 'Biography',
       'Comedy', 'Animation', 'Mystery', 'Horror', 'Film-Noir', 'Sci-Fi',
       'History', 'Thriller', 'Family', 'Fantasy'], dtype=object)

In [5]:
df["genre"].value_counts()

Drama        278
Comedy       156
Action       136
Crime        124
Biography     77
Adventure     75
Animation     62
Horror        29
Mystery       16
Western        9
Sci-Fi         5
Thriller       5
Film-Noir      3
Family         2
History        1
Fantasy        1
Name: genre, dtype: int64

In [6]:
len(df["genre"].unique())

16

In [7]:
df["genre"].nunique()

16

In [8]:
df["genre"].unique()

array(['Crime', 'Action', 'Drama', 'Western', 'Adventure', 'Biography',
       'Comedy', 'Animation', 'Mystery', 'Horror', 'Film-Noir', 'Sci-Fi',
       'History', 'Thriller', 'Family', 'Fantasy'], dtype=object)

In [9]:
df.groupby("genre")

In [10]:
df.groupby("genre").first()

,star_rating,title,content_rating,duration,actors_list
genre,,,,,
Action,9.0,The Dark Knight,PG-13,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
Adventure,8.9,The Lord of the Rings: The Return of the King,PG-13,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
Animation,8.6,Spirited Away,PG,125,"[u'Daveigh Chase', u'Suzanne Pleshette', u'Miy..."
Biography,8.9,Schindler's List,R,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
Comedy,8.6,Life Is Beautiful,PG-13,116,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G..."
Crime,9.3,The Shawshank Redemption,R,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
Drama,8.9,12 Angry Men,NOT RATED,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
Family,7.9,E.T. the Extra-Terrestrial,PG,115,"[u'Henry Thomas', u'Drew Barrymore', u'Peter C..."
Fantasy,7.7,The City of Lost Children,R,112,"[u'Ron Perlman', u'Daniel Emilfork', u'Judith ..."
Film-Noir,8.3,The Third Man,NOT RATED,93,"[u'Orson Welles', u'Joseph Cotten', u'Alida Va..."
History,8.0,Battleship Potemkin,UNRATED,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."
Horror,8.6,Psycho,R,109,"[u'Anthony Perkins', u'Janet Leigh', u'Vera Mi..."
Mystery,8.6,Rear Window,APPROVED,112,"[u'James Stewart', u'Grace Kelly', u'Wendell C..."
Sci-Fi,8.2,Blade Runner,R,117,"[u'Harrison Ford', u'Rutger Hauer', u'Sean You..."
Thriller,8.0,Shadow of a Doubt,APPROVED,108,"[u'Teresa Wright', u'Joseph Cotten', u'Macdona..."
Western,8.9,"The Good, the Bad and the Ugly",NOT RATED,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."

In [11]:
df.groupby("genre").get_group("Western")

,star_rating,title,content_rating,genre,duration,actors_list
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
26,8.6,Once Upon a Time in the West,PG-13,Western,175,"[u'Henry Fonda', u'Charles Bronson', u'Claudia..."
59,8.5,Django Unchained,R,Western,165,"[u'Jamie Foxx', u'Christoph Waltz', u'Leonardo..."
107,8.3,For a Few Dollars More,APPROVED,Western,132,"[u'Clint Eastwood', u'Lee Van Cleef', u'Gian M..."
119,8.3,Unforgiven,R,Western,131,"[u'Clint Eastwood', u'Gene Hackman', u'Morgan ..."
236,8.1,High Noon,PG,Western,85,"[u'Gary Cooper', u'Grace Kelly', u'Thomas Mitc..."
263,8.1,Rio Bravo,NOT RATED,Western,141,"[u'John Wayne', u'Dean Martin', u'Ricky Nelson']"
421,7.9,The Outlaw Josey Wales,PG,Western,135,"[u'Clint Eastwood', u'Sondra Locke', u'Chief D..."
704,7.6,High Plains Drifter,R,Western,105,"[u'Clint Eastwood', u'Verna Bloom', u'Marianna..."

In [12]:
df.groupby("genre").get_group("Fantasy")

,star_rating,title,content_rating,genre,duration,actors_list
638,7.7,The City of Lost Children,R,Fantasy,112,"[u'Ron Perlman', u'Daniel Emilfork', u'Judith ..."

In [13]:
df.groupby("genre").get_group("Fantasy")
df.reset_index()

,index,star_rating,title,content_rating,genre,duration,actors_list
0,0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...,...
974,974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [14]:
df.groupby("genre").get_group("Fantasy")
df.reset_index(drop=True)

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [15]:
df['content_rating'].unique()

array(['R', 'PG-13', 'NOT RATED', 'PG', 'UNRATED', 'APPROVED', 'PASSED',
       'G', 'X', nan, 'TV-MA', 'GP', 'NC-17'], dtype=object)

In [16]:
df['content_rating'].nunique()

12

In [17]:
df.groupby("content_rating").first()

,star_rating,title,genre,duration,actors_list
content_rating,,,,,
APPROVED,8.7,It's a Wonderful Life,Drama,130,"[u'James Stewart', u'Donna Reed', u'Lionel Bar..."
G,8.6,Modern Times,Comedy,87,"[u'Charles Chaplin', u'Paulette Goddard', u'He..."
GP,8.1,Harold and Maude,Comedy,91,"[u'Ruth Gordon', u'Bud Cort', u'Vivian Pickles']"
NC-17,7.9,Blue Is the Warmest Color,Drama,179,"[u'L\xe9a Seydoux', u'Ad\xe8le Exarchopoulos',..."
NOT RATED,8.9,12 Angry Men,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
PASSED,8.6,City Lights,Comedy,87,"[u'Charles Chaplin', u'Virginia Cherrill', u'F..."
PG,8.8,Star Wars: Episode V - The Empire Strikes Back,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
PG-13,9.0,The Dark Knight,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
R,9.3,The Shawshank Redemption,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
TV-MA,8.1,Who's Afraid of Virginia Woolf?,Drama,131,"[u'Elizabeth Taylor', u'Richard Burton', u'Geo..."
UNRATED,8.7,Seven Samurai,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
X,8.4,A Clockwork Orange,Crime,136,"[u'Malcolm McDowell', u'Patrick Magee', u'Mich..."

In [18]:
df['content_rating'].value_counts()

R            460
PG-13        189
PG           123
NOT RATED     65
APPROVED      47
UNRATED       38
G             32
PASSED         7
NC-17          7
X              4
GP             3
TV-MA          1
Name: content_rating, dtype: int64

In [19]:
df.groupby("content_rating").get_group("GP")

,star_rating,title,content_rating,genre,duration,actors_list
282,8.1,Harold and Maude,GP,Comedy,91,"[u'Ruth Gordon', u'Bud Cort', u'Vivian Pickles']"
302,8.0,Patton,GP,Biography,172,"[u'George C. Scott', u'Karl Malden', u'Stephen..."
691,7.7,Kelly's Heroes,GP,Action,144,"[u'Clint Eastwood', u'Telly Savalas', u'Don Ri..."

In [20]:
df.groupby("content_rating").get_group("PG")

,star_rating,title,content_rating,genre,duration,actors_list
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
30,8.6,Spirited Away,PG,Animation,125,"[u'Daveigh Chase', u'Suzanne Pleshette', u'Miy..."
32,8.6,Casablanca,PG,Drama,102,"[u'Humphrey Bogart', u'Ingrid Bergman', u'Paul..."
37,8.6,Raiders of the Lost Ark,PG,Action,115,"[u'Harrison Ford', u'Karen Allen', u'Paul Free..."
...,...,...,...,...,...,...
956,7.4,Manhattan Murder Mystery,PG,Comedy,104,"[u'Woody Allen', u'Diane Keaton', u'Jerry Adler']"
962,7.4,Driving Miss Daisy,PG,Comedy,99,"[u'Morgan Freeman', u'Jessica Tandy', u'Dan Ay..."
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."

In [23]:
 # For multiple categories pass a tuple of categories in get group
df.groupby(["content_rating","genre"]).get_group(("PG","Action"))

,star_rating,title,content_rating,genre,duration,actors_list
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
37,8.6,Raiders of the Lost Ark,PG,Action,115,"[u'Harrison Ford', u'Karen Allen', u'Paul Free..."
80,8.4,Star Wars: Episode VI - Return of the Jedi,PG,Action,134,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
327,8.0,The Adventures of Robin Hood,PG,Action,102,"[u'Errol Flynn', u'Olivia de Havilland', u'Bas..."
420,7.9,The Man Who Would Be King,PG,Action,129,"[u'Sean Connery', u'Michael Caine', u'Christop..."
586,7.7,Star Trek II: The Wrath of Khan,PG,Action,113,"[u'William Shatner', u'Leonard Nimoy', u'DeFor..."
748,7.6,The Hunt for Red October,PG,Action,135,"[u'Sean Connery', u'Alec Baldwin', u'Scott Gle..."
753,7.6,Escape from Alcatraz,PG,Action,112,"[u'Clint Eastwood', u'Patrick McGoohan', u'Rob..."
764,7.6,Indiana Jones and the Temple of Doom,PG,Action,118,"[u'Harrison Ford', u'Kate Capshaw', u'Jonathan..."
908,7.5,Bullitt,PG,Action,114,"[u'Steve McQueen', u'Jacqueline Bisset', u'Rob..."

In [24]:
df.groupby(["content_rating","genre"]).get_group(("PG","Action","Drama"))

ValueError: must supply a same-length tuple to get_group with multiple grouping keys

In [25]:
df.groupby(["content_rating","genre"]).get_group(("PG","Drama"))

,star_rating,title,content_rating,genre,duration,actors_list
32,8.6,Casablanca,PG,Drama,102,"[u'Humphrey Bogart', u'Ingrid Bergman', u'Paul..."
47,8.5,Taare Zameen Par,PG,Drama,165,"[u'Darsheel Safary', u'Aamir Khan', u'Tanay Ch..."
221,8.1,Solaris,PG,Drama,167,"[u'Natalya Bondarchuk', u'Donatas Banionis', u..."
250,8.1,In the Mood for Love,PG,Drama,98,"[u'Tony Chiu Wai Leung', u'Maggie Cheung', u'P..."
267,8.1,Jaws,PG,Drama,124,"[u'Roy Scheider', u'Robert Shaw', u'Richard Dr..."
269,8.1,Rocky,PG,Drama,119,"[u'Sylvester Stallone', u'Talia Shire', u'Burt..."
284,8.1,A Streetcar Named Desire,PG,Drama,122,"[u'Vivien Leigh', u'Marlon Brando', u'Kim Hunt..."
295,8.1,The Truman Show,PG,Drama,103,"[u'Jim Carrey', u'Ed Harris', u'Laura Linney']"
307,8.0,East of Eden,PG,Drama,115,"[u'James Dean', u'Raymond Massey', u'Julie Har..."
342,8.0,Dead Poets Society,PG,Drama,128,"[u'Robin Williams', u'Robert Sean Leonard', u'..."
347,8.0,Days of Heaven,PG,Drama,94,"[u'Richard Gere', u'Brooke Adams', u'Sam Shepa..."
398,7.9,The Conversation,PG,Drama,113,"[u'Gene Hackman', u'John Cazale', u'Allen Garf..."
404,7.9,The Remains of the Day,PG,Drama,134,"[u'Anthony Hopkins', u'Emma Thompson', u'John ..."
448,7.9,Cabaret,PG,Drama,124,"[u'Liza Minnelli', u'Michael York', u'Helmut G..."
504,7.8,Empire of the Sun,PG,Drama,153,"[u'Christian Bale', u'John Malkovich', u'Miran..."
525,7.8,Pride & Prejudice,PG,Drama,129,"[u'Keira Knightley', u'Matthew Macfadyen', u'B..."
634,7.7,Close Encounters of the Third Kind,PG,Drama,137,"[u'Richard Dreyfuss', u'Fran\xe7ois Truffaut',..."
645,7.7,Sense and Sensibility,PG,Drama,131,"[u'Emma Thompson', u'Kate Winslet', u'James Fl..."
775,7.6,Hoosiers,PG,Drama,114,"[u'Gene Hackman', u'Barbara Hershey', u'Dennis..."
800,7.6,Field of Dreams,PG,Drama,107,"[u'Kevin Costner', u'James Earl Jones', u'Ray ..."
813,7.6,The Natural,PG,Drama,138,"[u'Robert Redford', u'Robert Duvall', u'Glenn ..."
816,7.6,August Rush,PG,Drama,114,"[u'Freddie Highmore', u'Keri Russell', u'Jonat..."
822,7.5,"Good Night, and Good Luck.",PG,Drama,93,"[u'David Strathairn', u'George Clooney', u'Pat..."
854,7.5,Miracle,PG,Drama,135,"[u'Kurt Russell', u'Patricia Clarkson', u'Nath..."
941,7.4,A Bridge Too Far,PG,Drama,175,"[u'Sean Connery', u""Ryan O'Neal"", u'Michael Ca..."

In [26]:
df.groupby(["content_rating","genre"]).get_group(("PG","Drama")).sort_values("star_rating")

,star_rating,title,content_rating,genre,duration,actors_list
941,7.4,A Bridge Too Far,PG,Drama,175,"[u'Sean Connery', u""Ryan O'Neal"", u'Michael Ca..."
822,7.5,"Good Night, and Good Luck.",PG,Drama,93,"[u'David Strathairn', u'George Clooney', u'Pat..."
854,7.5,Miracle,PG,Drama,135,"[u'Kurt Russell', u'Patricia Clarkson', u'Nath..."
816,7.6,August Rush,PG,Drama,114,"[u'Freddie Highmore', u'Keri Russell', u'Jonat..."
813,7.6,The Natural,PG,Drama,138,"[u'Robert Redford', u'Robert Duvall', u'Glenn ..."
800,7.6,Field of Dreams,PG,Drama,107,"[u'Kevin Costner', u'James Earl Jones', u'Ray ..."
775,7.6,Hoosiers,PG,Drama,114,"[u'Gene Hackman', u'Barbara Hershey', u'Dennis..."
645,7.7,Sense and Sensibility,PG,Drama,131,"[u'Emma Thompson', u'Kate Winslet', u'James Fl..."
634,7.7,Close Encounters of the Third Kind,PG,Drama,137,"[u'Richard Dreyfuss', u'Fran\xe7ois Truffaut',..."
525,7.8,Pride & Prejudice,PG,Drama,129,"[u'Keira Knightley', u'Matthew Macfadyen', u'B..."
504,7.8,Empire of the Sun,PG,Drama,153,"[u'Christian Bale', u'John Malkovich', u'Miran..."
448,7.9,Cabaret,PG,Drama,124,"[u'Liza Minnelli', u'Michael York', u'Helmut G..."
404,7.9,The Remains of the Day,PG,Drama,134,"[u'Anthony Hopkins', u'Emma Thompson', u'John ..."
398,7.9,The Conversation,PG,Drama,113,"[u'Gene Hackman', u'John Cazale', u'Allen Garf..."
347,8.0,Days of Heaven,PG,Drama,94,"[u'Richard Gere', u'Brooke Adams', u'Sam Shepa..."
342,8.0,Dead Poets Society,PG,Drama,128,"[u'Robin Williams', u'Robert Sean Leonard', u'..."
307,8.0,East of Eden,PG,Drama,115,"[u'James Dean', u'Raymond Massey', u'Julie Har..."
295,8.1,The Truman Show,PG,Drama,103,"[u'Jim Carrey', u'Ed Harris', u'Laura Linney']"
284,8.1,A Streetcar Named Desire,PG,Drama,122,"[u'Vivien Leigh', u'Marlon Brando', u'Kim Hunt..."
269,8.1,Rocky,PG,Drama,119,"[u'Sylvester Stallone', u'Talia Shire', u'Burt..."
267,8.1,Jaws,PG,Drama,124,"[u'Roy Scheider', u'Robert Shaw', u'Richard Dr..."
250,8.1,In the Mood for Love,PG,Drama,98,"[u'Tony Chiu Wai Leung', u'Maggie Cheung', u'P..."
221,8.1,Solaris,PG,Drama,167,"[u'Natalya Bondarchuk', u'Donatas Banionis', u..."
47,8.5,Taare Zameen Par,PG,Drama,165,"[u'Darsheel Safary', u'Aamir Khan', u'Tanay Ch..."
32,8.6,Casablanca,PG,Drama,102,"[u'Humphrey Bogart', u'Ingrid Bergman', u'Paul..."

In [27]:
df.groupby(["content_rating","genre"]).get_group(("PG","Drama")).sort_values("star_rating",ascending=False)

,star_rating,title,content_rating,genre,duration,actors_list
32,8.6,Casablanca,PG,Drama,102,"[u'Humphrey Bogart', u'Ingrid Bergman', u'Paul..."
47,8.5,Taare Zameen Par,PG,Drama,165,"[u'Darsheel Safary', u'Aamir Khan', u'Tanay Ch..."
221,8.1,Solaris,PG,Drama,167,"[u'Natalya Bondarchuk', u'Donatas Banionis', u..."
250,8.1,In the Mood for Love,PG,Drama,98,"[u'Tony Chiu Wai Leung', u'Maggie Cheung', u'P..."
267,8.1,Jaws,PG,Drama,124,"[u'Roy Scheider', u'Robert Shaw', u'Richard Dr..."
269,8.1,Rocky,PG,Drama,119,"[u'Sylvester Stallone', u'Talia Shire', u'Burt..."
284,8.1,A Streetcar Named Desire,PG,Drama,122,"[u'Vivien Leigh', u'Marlon Brando', u'Kim Hunt..."
295,8.1,The Truman Show,PG,Drama,103,"[u'Jim Carrey', u'Ed Harris', u'Laura Linney']"
307,8.0,East of Eden,PG,Drama,115,"[u'James Dean', u'Raymond Massey', u'Julie Har..."
342,8.0,Dead Poets Society,PG,Drama,128,"[u'Robin Williams', u'Robert Sean Leonard', u'..."
347,8.0,Days of Heaven,PG,Drama,94,"[u'Richard Gere', u'Brooke Adams', u'Sam Shepa..."
448,7.9,Cabaret,PG,Drama,124,"[u'Liza Minnelli', u'Michael York', u'Helmut G..."
404,7.9,The Remains of the Day,PG,Drama,134,"[u'Anthony Hopkins', u'Emma Thompson', u'John ..."
398,7.9,The Conversation,PG,Drama,113,"[u'Gene Hackman', u'John Cazale', u'Allen Garf..."
504,7.8,Empire of the Sun,PG,Drama,153,"[u'Christian Bale', u'John Malkovich', u'Miran..."
525,7.8,Pride & Prejudice,PG,Drama,129,"[u'Keira Knightley', u'Matthew Macfadyen', u'B..."
634,7.7,Close Encounters of the Third Kind,PG,Drama,137,"[u'Richard Dreyfuss', u'Fran\xe7ois Truffaut',..."
645,7.7,Sense and Sensibility,PG,Drama,131,"[u'Emma Thompson', u'Kate Winslet', u'James Fl..."
775,7.6,Hoosiers,PG,Drama,114,"[u'Gene Hackman', u'Barbara Hershey', u'Dennis..."
800,7.6,Field of Dreams,PG,Drama,107,"[u'Kevin Costner', u'James Earl Jones', u'Ray ..."
813,7.6,The Natural,PG,Drama,138,"[u'Robert Redford', u'Robert Duvall', u'Glenn ..."
816,7.6,August Rush,PG,Drama,114,"[u'Freddie Highmore', u'Keri Russell', u'Jonat..."
822,7.5,"Good Night, and Good Luck.",PG,Drama,93,"[u'David Strathairn', u'George Clooney', u'Pat..."
854,7.5,Miracle,PG,Drama,135,"[u'Kurt Russell', u'Patricia Clarkson', u'Nath..."
941,7.4,A Bridge Too Far,PG,Drama,175,"[u'Sean Connery', u""Ryan O'Neal"", u'Michael Ca..."

In [28]:
df.groupby(["content_rating","genre"]).get_group(("PG","Drama")).sort_values("duration",ascending=False)

,star_rating,title,content_rating,genre,duration,actors_list
941,7.4,A Bridge Too Far,PG,Drama,175,"[u'Sean Connery', u""Ryan O'Neal"", u'Michael Ca..."
221,8.1,Solaris,PG,Drama,167,"[u'Natalya Bondarchuk', u'Donatas Banionis', u..."
47,8.5,Taare Zameen Par,PG,Drama,165,"[u'Darsheel Safary', u'Aamir Khan', u'Tanay Ch..."
504,7.8,Empire of the Sun,PG,Drama,153,"[u'Christian Bale', u'John Malkovich', u'Miran..."
813,7.6,The Natural,PG,Drama,138,"[u'Robert Redford', u'Robert Duvall', u'Glenn ..."
634,7.7,Close Encounters of the Third Kind,PG,Drama,137,"[u'Richard Dreyfuss', u'Fran\xe7ois Truffaut',..."
854,7.5,Miracle,PG,Drama,135,"[u'Kurt Russell', u'Patricia Clarkson', u'Nath..."
404,7.9,The Remains of the Day,PG,Drama,134,"[u'Anthony Hopkins', u'Emma Thompson', u'John ..."
645,7.7,Sense and Sensibility,PG,Drama,131,"[u'Emma Thompson', u'Kate Winslet', u'James Fl..."
525,7.8,Pride & Prejudice,PG,Drama,129,"[u'Keira Knightley', u'Matthew Macfadyen', u'B..."
342,8.0,Dead Poets Society,PG,Drama,128,"[u'Robin Williams', u'Robert Sean Leonard', u'..."
267,8.1,Jaws,PG,Drama,124,"[u'Roy Scheider', u'Robert Shaw', u'Richard Dr..."
448,7.9,Cabaret,PG,Drama,124,"[u'Liza Minnelli', u'Michael York', u'Helmut G..."
284,8.1,A Streetcar Named Desire,PG,Drama,122,"[u'Vivien Leigh', u'Marlon Brando', u'Kim Hunt..."
269,8.1,Rocky,PG,Drama,119,"[u'Sylvester Stallone', u'Talia Shire', u'Burt..."
307,8.0,East of Eden,PG,Drama,115,"[u'James Dean', u'Raymond Massey', u'Julie Har..."
775,7.6,Hoosiers,PG,Drama,114,"[u'Gene Hackman', u'Barbara Hershey', u'Dennis..."
816,7.6,August Rush,PG,Drama,114,"[u'Freddie Highmore', u'Keri Russell', u'Jonat..."
398,7.9,The Conversation,PG,Drama,113,"[u'Gene Hackman', u'John Cazale', u'Allen Garf..."
800,7.6,Field of Dreams,PG,Drama,107,"[u'Kevin Costner', u'James Earl Jones', u'Ray ..."
295,8.1,The Truman Show,PG,Drama,103,"[u'Jim Carrey', u'Ed Harris', u'Laura Linney']"
32,8.6,Casablanca,PG,Drama,102,"[u'Humphrey Bogart', u'Ingrid Bergman', u'Paul..."
250,8.1,In the Mood for Love,PG,Drama,98,"[u'Tony Chiu Wai Leung', u'Maggie Cheung', u'P..."
347,8.0,Days of Heaven,PG,Drama,94,"[u'Richard Gere', u'Brooke Adams', u'Sam Shepa..."
822,7.5,"Good Night, and Good Luck.",PG,Drama,93,"[u'David Strathairn', u'George Clooney', u'Pat..."

In [29]:
df.loc[:,:]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [30]:
df.loc[:,["title"]]

                                               title
0                           The Shawshank Redemption
1                                      The Godfather
2                             The Godfather: Part II
3                                    The Dark Knight
4                                       Pulp Fiction
..                                               ...
974                                          Tootsie
975                      Back to the Future Part III
976  Master and Commander: The Far Side of the World
977                                      Poltergeist
978                                      Wall Street

[979 rows x 1 columns]

In [31]:
df.loc[:,["title","genre"]]

                                               title      genre
0                           The Shawshank Redemption      Crime
1                                      The Godfather      Crime
2                             The Godfather: Part II      Crime
3                                    The Dark Knight     Action
4                                       Pulp Fiction      Crime
..                                               ...        ...
974                                          Tootsie     Comedy
975                      Back to the Future Part III  Adventure
976  Master and Commander: The Far Side of the World     Action
977                                      Poltergeist     Horror
978                                      Wall Street      Crime

[979 rows x 2 columns]

In [32]:
df.loc[df["genre"] == "Action"]

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
20,8.7,The Matrix,R,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
...,...,...,...,...,...,...
918,7.5,Running Scared,R,Action,122,"[u'Paul Walker', u'Cameron Bright', u'Chazz Pa..."
954,7.4,X-Men,PG-13,Action,104,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc..."
963,7.4,La Femme Nikita,R,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."

In [33]:
df["genre"] == "Action"

0      False
1      False
2      False
3       True
4      False
       ...
974    False
975    False
976     True
977    False
978    False
Name: genre, Length: 979, dtype: bool

In [35]:
df.loc[df["content_rating"] == "PG"]

,star_rating,title,content_rating,genre,duration,actors_list
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
30,8.6,Spirited Away,PG,Animation,125,"[u'Daveigh Chase', u'Suzanne Pleshette', u'Miy..."
32,8.6,Casablanca,PG,Drama,102,"[u'Humphrey Bogart', u'Ingrid Bergman', u'Paul..."
37,8.6,Raiders of the Lost Ark,PG,Action,115,"[u'Harrison Ford', u'Karen Allen', u'Paul Free..."
...,...,...,...,...,...,...
956,7.4,Manhattan Murder Mystery,PG,Comedy,104,"[u'Woody Allen', u'Diane Keaton', u'Jerry Adler']"
962,7.4,Driving Miss Daisy,PG,Comedy,99,"[u'Morgan Freeman', u'Jessica Tandy', u'Dan Ay..."
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."

In [38]:
df.loc[(df["genre"] == "Action") | (df["content_rating"] == "PG")].sort_values("star_rating")

,star_rating,title,content_rating,genre,duration,actors_list
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
933,7.4,Beetlejuice,PG,Comedy,92,"[u'Alec Baldwin', u'Geena Davis', u'Michael Ke..."
937,7.4,Labyrinth,PG,Adventure,101,"[u'David Bowie', u'Jennifer Connelly', u'Toby ..."
941,7.4,A Bridge Too Far,PG,Drama,175,"[u'Sean Connery', u""Ryan O'Neal"", u'Michael Ca..."
949,7.4,Home Alone,PG,Comedy,103,"[u'Macaulay Culkin', u'Joe Pesci', u'Daniel St..."
...,...,...,...,...,...,...
20,8.7,The Matrix,R,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."

In [37]:
df.loc[(df["genre"] == "Action") & (df["content_rating"] == "PG")]

,star_rating,title,content_rating,genre,duration,actors_list
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
37,8.6,Raiders of the Lost Ark,PG,Action,115,"[u'Harrison Ford', u'Karen Allen', u'Paul Free..."
80,8.4,Star Wars: Episode VI - Return of the Jedi,PG,Action,134,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
327,8.0,The Adventures of Robin Hood,PG,Action,102,"[u'Errol Flynn', u'Olivia de Havilland', u'Bas..."
420,7.9,The Man Who Would Be King,PG,Action,129,"[u'Sean Connery', u'Michael Caine', u'Christop..."
586,7.7,Star Trek II: The Wrath of Khan,PG,Action,113,"[u'William Shatner', u'Leonard Nimoy', u'DeFor..."
748,7.6,The Hunt for Red October,PG,Action,135,"[u'Sean Connery', u'Alec Baldwin', u'Scott Gle..."
753,7.6,Escape from Alcatraz,PG,Action,112,"[u'Clint Eastwood', u'Patrick McGoohan', u'Rob..."
764,7.6,Indiana Jones and the Temple of Doom,PG,Action,118,"[u'Harrison Ford', u'Kate Capshaw', u'Jonathan..."
908,7.5,Bullitt,PG,Action,114,"[u'Steve McQueen', u'Jacqueline Bisset', u'Rob..."

In [39]:
df.loc[df['star_rating'] > 5]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [40]:
df.loc[df['star_rating'] < 5]

Empty DataFrame
Columns: [star_rating, title, content_rating, genre, duration, actors_list]
Index: []

In [43]:
df.loc[df['star_rating'] > 9]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."